/**
 * Extract league URLs from Sportstats365 fixtures page
 * This scrapes the actual leagues that appear on the main page
 */

import httpClient from './http-client';
import * as cheerio from 'cheerio';
import * as fs from 'fs';

interface LeagueInfo {
  name: string;
  slug: string;
  url: string;
}

async function fetchPage(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    httpClient.get({
      uri: url,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'HX-Request': 'true',
      },
    }, (error: any, response: any, body: string) => {
      if (error) {
        reject(error);
      } else {
        resolve(body);
      }
    });
  });
}

async function extractLeaguesFromDate(dateString: string): Promise<LeagueInfo[]> {
  const url = `https://sportstats365.com/football?start=${dateString}`;
  console.log(`Scraping: ${url}`);
  
  try {
    const html = await fetchPage(url);
    const $ = cheerio.load(html);
    const leagues: Map<string, LeagueInfo> = new Map();
    
    // Find all competition headers
    $('.list-group-item.text-muted.border-0').each((index, element) => {
      const $item = $(element);
      const competitionLink = $item.find('a').first();
      const href = competitionLink.attr('href');
      const name = competitionLink.text().trim();
      
      if (href && name) {
        // Extract slug from URL
        const match = href.match(/^\/football\/([^\/\?]+)/);
        if (match) {
          const slug = match[1];
          const fullUrl = `https://sportstats365.com${href}`;
          
          // Use slug as key to avoid duplicates
          if (!leagues.has(slug)) {
            leagues.set(slug, {
              name,
              slug,
              url: fullUrl,
            });
          }
        }
      }
    });
    
    return Array.from(leagues.values());
  } catch (error) {
    console.error(`Error scraping ${dateString}:`, error);
    return [];
  }
}

async function scrapeMultipleDates(numDays: number = 30): Promise<LeagueInfo[]> {
  const allLeagues: Map<string, LeagueInfo> = new Map();
  const today = new Date();
  
  console.log(`Scraping ${numDays} days of fixtures to discover all leagues...\n`);
  
  for (let i = -15; i < numDays - 15; i++) {
    const date = new Date(today);
    date.setDate(date.getDate() + i);
    
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, '0');
    const day = String(date.getDate()).padStart(2, '0');
    const dateString = `${year}-${month}-${day}`;
    
    const leagues = await extractLeaguesFromDate(dateString);
    
    leagues.forEach(league => {
      if (!allLeagues.has(league.slug)) {
        allLeagues.set(league.slug, league);
      }
    });
    
    console.log(`  ${dateString}: Found ${leagues.length} leagues (total unique: ${allLeagues.size})`);
    
    // Be polite to the server
    await new Promise(resolve => setTimeout(resolve, 1500));
  }
  
  return Array.from(allLeagues.values());
}

function cleanLeagueName(name: string): string {
  // Remove year suffixes
  return name.replace(/\s+\d{4}(\/\d{4})?$/g, '').trim();
}

function generateMappingFile(leagues: LeagueInfo[]): string {
  // Sort by name
  leagues.sort((a, b) => a.name.localeCompare(b.name));
  
  let content = `/**
 * VERIFIED LEAGUE URL MAPPINGS FROM SPORTSTATS365
 * 
 * This file was auto-generated by scraping actual fixtures from Sportstats365.
 * Each mapping represents a league that appears on the site.
 * 
 * Generated by: server/extract-league-urls-from-fixtures.ts
 * Last updated: ${new Date().toISOString()}
 * Total leagues: ${leagues.length}
 */

export const VERIFIED_LEAGUE_MAPPINGS: Record<string, string> = {\n`;
  
  leagues.forEach(league => {
    const cleanName = cleanLeagueName(league.name);
    content += `  '${cleanName}': '${league.slug}',\n`;
  });
  
  content += `};\n\n`;
  
  // Add helper function
  content += `/**
 * Get league slug for a competition name
 * Automatically removes year suffixes
 */
export function getVerifiedLeagueSlug(competitionName: string): string | null {
  // Remove year suffix (e.g., " 2025/2026" or " 2025")
  const cleanName = competitionName.replace(/\\s+\\d{4}(\\/\\d{4})?$/g, '').trim();
  
  // Try direct mapping
  if (VERIFIED_LEAGUE_MAPPINGS[cleanName]) {
    return VERIFIED_LEAGUE_MAPPINGS[cleanName];
  }
  
  // Try case-insensitive search
  const lowerCleanName = cleanName.toLowerCase();
  for (const [key, value] of Object.entries(VERIFIED_LEAGUE_MAPPINGS)) {
    if (key.toLowerCase() === lowerCleanName) {
      return value;
    }
  }
  
  return null;
}\n`;
  
  return content;
}

async function main() {
  console.log('Extracting league URLs from Sportstats365 fixtures...\n');
  
  const leagues = await scrapeMultipleDates(30);
  
  console.log(`\n=== EXTRACTION COMPLETE ===`);
  console.log(`Total unique leagues found: ${leagues.length}`);
  
  // Generate the mapping file
  const mappingContent = generateMappingFile(leagues);
  fs.writeFileSync('server/verified-league-mappings.ts', mappingContent);
  console.log('\nMapping file saved to: server/verified-league-mappings.ts');
  
  // Generate a detailed report
  const report = {
    totalLeagues: leagues.length,
    timestamp: new Date().toISOString(),
    leagues: leagues.map(l => ({
      name: l.name,
      slug: l.slug,
      url: l.url,
    })),
  };
  
  fs.writeFileSync('server/league-extraction-report.json', JSON.stringify(report, null, 2));
  console.log('Report saved to: server/league-extraction-report.json\n');
  
  // Show sample mappings
  console.log('=== SAMPLE MAPPINGS ===');
  leagues.slice(0, 10).forEach(league => {
    console.log(`  "${cleanLeagueName(league.name)}" -> "${league.slug}"`);
  });
  
  console.log('\n✅ Extraction complete! Use the verified mappings in your scraper.');
}

main().catch(console.error);
