/**
 * Scrape Sportstats365's official competitions/leagues page
 * This gets ALL leagues with their EXACT URLs directly from the site
 */

import httpClient from './http-client';
import * as cheerio from 'cheerio';
import * as fs from 'fs';

interface LeagueInfo {
  name: string;
  slug: string;
  url: string;
  region?: string;
  country?: string;
}

async function fetchPage(url: string): Promise<string> {
  return new Promise((resolve, reject) => {
    httpClient.get({
      uri: url,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
      },
    }, (error: any, response: any, body: string) => {
      if (error) {
        reject(error);
      } else {
        resolve(body);
      }
    });
  });
}

async function scrapeCompetitionsPage(): Promise<LeagueInfo[]> {
  const url = 'https://sportstats365.com/football/competitions/leagues';
  console.log(`Scraping official competitions page: ${url}\n`);
  
  try {
    const html = await fetchPage(url);
    const $ = cheerio.load(html);
    const leagues: Map<string, LeagueInfo> = new Map();
    
    console.log('Extracting league links...');
    
    // Find all links to football leagues
    $('a[href^="/football/"]').each((index, element) => {
      const $link = $(element);
      const href = $link.attr('href');
      const text = $link.text().trim();
      
      if (!href || !text) return;
      
      // Skip non-league links
      const skipPatterns = [
        '/football/competitions',
        '/football/live',
        '/football/today',
        '/football/tomorrow',
        '/football/yesterday',
        '/football$',
        'javascript:',
        '#',
      ];
      
      if (skipPatterns.some(pattern => href.match(new RegExp(pattern)))) {
        return;
      }
      
      // Extract slug from URL pattern: /football/{slug} or /football/{slug}/season
      const match = href.match(/^\/football\/([^\/\?#]+)/);
      if (match) {
        const slug = match[1];
        
        // Skip if it's a common navigation term
        if (['countries', 'competitions', 'leagues'].includes(slug)) {
          return;
        }
        
        const fullUrl = `https://sportstats365.com${href}`;
        
        // Use slug as key to avoid duplicates
        if (!leagues.has(slug)) {
          leagues.set(slug, {
            name: text,
            slug,
            url: fullUrl,
          });
        }
      }
    });
    
    console.log(`Found ${leagues.size} unique league slugs\n`);
    return Array.from(leagues.values());
    
  } catch (error) {
    console.error('Error scraping competitions page:', error);
    return [];
  }
}

function cleanLeagueName(name: string): string {
  // Remove year suffixes and extra whitespace
  return name
    .replace(/\s+\d{4}(\/\d{4})?$/g, '')
    .replace(/\s+\(\d{4}(\/\d{4})?\)$/g, '')
    .trim();
}

function generateMappingFile(leagues: LeagueInfo[]): string {
  // Sort by name for easier reading
  leagues.sort((a, b) => cleanLeagueName(a.name).localeCompare(cleanLeagueName(b.name)));
  
  let content = `/**
 * VERIFIED LEAGUE URL MAPPINGS FROM SPORTSTATS365
 * 
 * This file was auto-generated by scraping:
 * https://sportstats365.com/football/competitions/leagues
 * 
 * Each mapping represents the OFFICIAL league slug from Sportstats365.
 * These are 100% accurate because they come directly from the site.
 * 
 * Generated by: server/scrape-competitions-page.ts
 * Last updated: ${new Date().toISOString()}
 * Total leagues: ${leagues.length}
 * 
 * IMPORTANT: The slugs here are the REAL ones from the site.
 * For example:
 *   - "Premier League" -> "premiership" (NOT "premier-league")
 *   - "Jupiler League" -> "1e-klasse" (NOT "jupiler-league")
 *   - "La Liga 2" -> Different from what you'd guess
 * 
 * DO NOT try to construct URLs manually - always use this mapping!
 */

export const VERIFIED_LEAGUE_MAPPINGS: Record<string, string> = {\n`;
  
  leagues.forEach(league => {
    const cleanName = cleanLeagueName(league.name);
    // Escape single quotes in league names
    const escapedName = cleanName.replace(/'/g, "\\'");
    content += `  '${escapedName}': '${league.slug}',\n`;
  });
  
  content += `};\n\n`;
  
  // Add helper function
  content += `/**
 * Get league slug for a competition name
 * Automatically removes year suffixes and handles variations
 * 
 * @param competitionName - The name of the competition (e.g., "Premier League 2025/2026")
 * @returns The verified slug from Sportstats365, or null if not found
 */
export function getVerifiedLeagueSlug(competitionName: string): string | null {
  // Remove year suffix (e.g., " 2025/2026" or " 2025")
  const cleanName = competitionName
    .replace(/\\s+\\d{4}(\\/\\d{4})?$/g, '')
    .replace(/\\s+\\(\\d{4}(\\/\\d{4})?\\)$/g, '')
    .trim();
  
  // Try direct mapping (case-sensitive first)
  if (VERIFIED_LEAGUE_MAPPINGS[cleanName]) {
    return VERIFIED_LEAGUE_MAPPINGS[cleanName];
  }
  
  // Try case-insensitive search
  const lowerCleanName = cleanName.toLowerCase();
  for (const [key, value] of Object.entries(VERIFIED_LEAGUE_MAPPINGS)) {
    if (key.toLowerCase() === lowerCleanName) {
      return value;
    }
  }
  
  // Try with common variations
  // For example: "England Premier League" vs "Premier League"
  const nameVariations = [
    cleanName.replace(/^(England|Spain|Germany|Italy|France)\\s+/i, ''),
    cleanName.replace(/^(UEFA|FIFA|AFC|CAF|CONCACAF|CONMEBOL|OFC)\\s+/i, ''),
  ];
  
  for (const variation of nameVariations) {
    if (variation !== cleanName && VERIFIED_LEAGUE_MAPPINGS[variation]) {
      return VERIFIED_LEAGUE_MAPPINGS[variation];
    }
  }
  
  return null;
}

/**
 * Get the full URL for a competition
 * 
 * @param competitionName - The name of the competition
 * @returns The full Sportstats365 URL, or null if not found
 */
export function getLeagueUrl(competitionName: string): string | null {
  const slug = getVerifiedLeagueSlug(competitionName);
  return slug ? \`https://sportstats365.com/football/\${slug}\` : null;
}\n`;
  
  return content;
}

async function main() {
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('SCRAPING SPORTSTATS365 OFFICIAL COMPETITIONS PAGE');
  console.log('This will extract the REAL league URLs from the site');
  console.log('═══════════════════════════════════════════════════════════════\n');
  
  const leagues = await scrapeCompetitionsPage();
  
  if (leagues.length === 0) {
    console.error('❌ Failed to extract any leagues!');
    process.exit(1);
  }
  
  console.log('═══════════════════════════════════════════════════════════════');
  console.log(`✅ SUCCESS! Found ${leagues.length} unique leagues`);
  console.log('═══════════════════════════════════════════════════════════════\n');
  
  // Generate the mapping file
  const mappingContent = generateMappingFile(leagues);
  fs.writeFileSync('server/verified-league-mappings.ts', mappingContent);
  console.log('📝 Mapping file saved to: server/verified-league-mappings.ts\n');
  
  // Generate a detailed report
  const report = {
    source: 'https://sportstats365.com/football/competitions/leagues',
    totalLeagues: leagues.length,
    timestamp: new Date().toISOString(),
    leagues: leagues.map(l => ({
      name: l.name,
      cleanName: cleanLeagueName(l.name),
      slug: l.slug,
      url: l.url,
    })),
  };
  
  fs.writeFileSync('server/league-scraping-report.json', JSON.stringify(report, null, 2));
  console.log('📋 Report saved to: server/league-scraping-report.json\n');
  
  // Show some examples
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('EXAMPLE MAPPINGS (showing first 20):');
  console.log('═══════════════════════════════════════════════════════════════\n');
  
  leagues.slice(0, 20).forEach(league => {
    const cleanName = cleanLeagueName(league.name);
    console.log(`  "${cleanName}"`);
    console.log(`    → slug: "${league.slug}"`);
    console.log(`    → URL: ${league.url}\n`);
  });
  
  console.log('═══════════════════════════════════════════════════════════════');
  console.log('✅ COMPLETE! Verified mappings are ready to use.');
  console.log('═══════════════════════════════════════════════════════════════');
}

main().catch(console.error);
