/**
 * VERIFIED LEAGUE URL MAPPINGS FROM SPORTSTATS365
 * 
 * This file was auto-generated by scraping actual fixtures from Sportstats365.
 * Each mapping represents a league that appears on the site.
 * 
 * Generated by: server/extract-league-urls-from-fixtures.ts
 * Last updated: 2025-11-03T14:56:07.972Z
 * Total leagues: 121
 */

export const VERIFIED_LEAGUE_MAPPINGS: Record<string, string> = {
  'Albania Super League': 'super-league',
  'Argentina Liga Profesional': 'primera-division',
  'Australia A-League': 'a-league',
  'Austria 2. Liga': '1-liga-at',
  'Austria Admiral Bundesliga': 'bundesliga-at',
  'Austria ÖFB Stiegl Cup': 'ofb-stiegl-cup',
  'Belarus Vysheyshaya Liga': 'premier-league',
  'Belgian Cup': 'beker-van-belgie',
  'Belgium Challenger Pro League': '2e-klasse',
  'Belgium Jupiler League': '1e-klasse',
  'Bosnia & Herzegovina Premier Liga': 'premier-liga',
  'Brazil Série A': 'serie-a-br',
  'Bulgaria Parva Liga': 'a-pfg',
  'Chile Primera División': 'primera-division-cl',
  'Colombia Primera A': 'primera-division-co',
  'Copa del Rey': 'copa-del-rey',
  'Copa Libertadores': 'copa-libertadores',
  'Copa Sudamericana': 'copa-sudamericana',
  'Croatia 1. HNL': '1-hnl',
  'Czech Cup': 'czech-cup',
  'Czechia FNL': '2-liga',
  'Czechia Fortuna Liga': '1-liga',
  'Danish Landspokal': 'landspokal',
  'Denmark 1st Division': '1st-division',
  'Denmark Superliga': 'superligaen',
  'DFB Cup': 'dfb-pokal',
  'Ecuador Liga Pro': 'primera-a',
  'England Carling Cup': 'carling-cup',
  'England Championship': 'championship',
  'England FA Cup': 'fa-cup',
  'England FA Trophy': 'fa-trophy',
  'England LDV Trophy': 'ldv-trophy',
  'England League One': 'league-one',
  'England League Two': 'league-two',
  'England National League': 'conference-national',
  'England Premier League': 'premiership',
  'Estonia Meistriliiga': 'meistriliiga',
  'Finland Veikkausliiga': 'veikkausliiga',
  'France Championnat National': 'national',
  'France Ligue 1': 'ligue-1',
  'France Ligue 2': 'ligue-2',
  'Germany 2. Bundesliga': '2-liga-de',
  'Germany 3. Liga': '3-liga',
  'Germany Bundesliga': 'bundesliga',
  'Greece Super League 2': 'b-ethniki',
  'Greece Super League': 'super-league-gr',
  'Greek Cup': 'cup-gr',
  'HR Nogometni Cup': 'hr-nogometni-cup',
  'Hungarian Cup': 'magyar-kupa',
  'Hungary NB II': 'nb-ii',
  'Hungary OTP Bank Liga NB1': 'nb-i',
  'Iceland Besta Deild Karla': 'landsbankadeild-karla',
  'International Friendlies': 'friendly-m',
  'Ireland FAI Cup': 'fai-cup',
  'Ireland First Division': 'division-1',
  'Ireland Premier Division': 'premier-league-ie',
  'Israel Premier League': 'ligat-al',
  'Italy Serie A': 'serie-a',
  'Italy Serie B': 'serie-b',
  'Japan J League': 'j-league',
  'Latvia Virsliga': 'virsliga',
  'Lithuania A Lyga': 'a-lyga',
  'Mexico Liga BBVA MX': 'primera-division-mx',
  'Moldavia Super Liga': 'divizia-nationala',
  'Montenegro 1. CFL League': 'prva-liga',
  'Netherlands Eerste Divisie': 'eerste-divisie',
  'Netherlands Eredivisie': 'eredivisie',
  'Netherlands KNVB Beker': 'knvb-beker',
  'North Macedonia First League': 'first-league',
  'Norway Eliteserien': 'tippeligaen',
  'Norway OBOS-ligaen': 'adeccoligaen',
  'Poland Ekstraklasa': 'ekstraklasa',
  'Poland I Liga': 'i-liga',
  'Polish Cup': 'puchar-polski',
  'Portugal Liga Portugal 2': 'liga-vitalis',
  'Portugal Liga Portugal': 'liga-sagres',
  'Romania Liga I': 'liga-i',
  'Romania Liga II': 'liga-ii',
  'Romanian Cup': 'cupa-romaniei',
  'Russia Premier League': 'premier-league-ru',
  'Russian Cup': 'cup',
  'Scotland Challenge Cup': 'challenge-cup',
  'Scotland League Cup': 'league-cup-sx',
  'Scotland Scottish Championship': 'first-division',
  'Scotland Scottish League One': 'second-division',
  'Scotland Scottish League Two': 'third-division',
  'Scotland Scottish Premiership': 'premier-league-sx',
  'Scottish Cup': 'scottish-cup',
  'Serbia Super Liga': 'super-liga-rs',
  'Serbian Cup': 'cup-rs',
  'Singapore S-League': 's-league',
  'Slovakia Niké Liga': 'super-liga',
  'Slovakian Cup': 'cup-sk',
  'Slovenia 2. Liga SNL': '2-snl',
  'Slovenia Prva Liga': '1-snl',
  'Slovenian Cup': 'cup-si',
  'Spain La Liga 2': 'liga-bbva',
  'Spain La Liga': 'la-liga',
  'Spain Primera RFEF - Group I': 'segunda-b-group-i',
  'Spain Primera RFEF - Group II': 'segunda-b-group-ii',
  'Sweden Allsvenskan': 'allsvenskan',
  'Sweden Superettan': 'superettan',
  'Switzerland Challenge League': 'challenge-league',
  'Switzerland Super League': 'super-league-ch',
  'Taça de Portugal': 'taca-de-portugal',
  'Turkey Süper Lig': 'super-league-tr',
  'Türkiye Kupasi': 'turkiye-kupasi',
  'UEFA Champions League': 'champions-league',
  'UEFA Europa Conference League': 'uefa-europa-conference-league',
  'UEFA Europa League': 'europa-league',
  'Ukraine Premier League': 'premier-league-ua',
  'Ukranian Cup': 'cup-ua',
  'United States MLS': 'mls',
  'Uruguay Primera División': 'primera-division-uy',
  'Venezuela Primera División': 'primera-division-ve',
  'Wales FA Cup': 'cup-wa',
  'Wales Premier League': 'premier-league-wa',
  'World Cup Qualifiers - Africa': 'world-cup-q-africa',
  'World Cup Qualifiers - Asia': 'world-cup-q-asia',
  'World Cup Qualifiers - Europe': 'world-cup-q-europe',
  'World Cup Qualifiers - N+C America': 'world-cup-q-n-c-america',
  'World Cup Qualifiers - South America': 'world-cup-q-conmebol',
};

/**
 * Normalize a league name for matching by:
 * - Removing year suffixes
 * - Removing leading country/confederation names
 * - Normalizing whitespace
 * - Converting to lowercase
 * - Normalizing accents and special characters
 */
function normalizeLeagueName(name: string): string {
  // Remove year suffix (e.g., " 2025/2026" or " 2025")
  let normalized = name.replace(/\s+\d{4}(\/\d{4})?$/g, '').trim();
  
  // List of country/region prefixes to remove
  const prefixes = [
    'England', 'Spain', 'Germany', 'Italy', 'France', 'Portugal', 'Netherlands',
    'Belgium', 'Turkey', 'Scotland', 'Wales', 'Ireland', 'Denmark', 'Sweden',
    'Norway', 'Poland', 'Czechia', 'Czech', 'Croatia', 'Greece', 'Hungary',
    'Romania', 'Serbia', 'Bulgaria', 'Austria', 'Switzerland', 'Russia',
    'Ukraine', 'Slovakia', 'Slovenia', 'Albania', 'Belarus', 'Bosnia & Herzegovina',
    'Bosnia', 'Estonia', 'Finland', 'Iceland', 'Latvia', 'Lithuania',
    'Moldova', 'Moldavia', 'Montenegro', 'North Macedonia', 'Macedonia',
    'Israel', 'United States', 'USA', 'Mexico', 'Argentina', 'Brazil',
    'Chile', 'Colombia', 'Uruguay', 'Venezuela', 'Ecuador', 'Paraguay', 'Peru',
    'Japan', 'Singapore', 'Australia', 'China', 'South Korea',
    'UEFA', 'FIFA', 'AFC', 'CAF', 'CONCACAF', 'CONMEBOL', 'OFC',
  ];
  
  // Remove leading country/confederation prefix
  for (const prefix of prefixes) {
    const pattern = new RegExp(`^${prefix}\\s+`, 'i');
    normalized = normalized.replace(pattern, '');
  }
  
  // Remove leading numbers and dots (e.g., "1. HNL" -> "HNL", "2. Liga" -> "Liga")
  normalized = normalized.replace(/^(\d+\.?\s+)/, '');
  
  // Normalize whitespace
  normalized = normalized.replace(/\s+/g, ' ').trim();
  
  // Convert to lowercase for case-insensitive matching
  normalized = normalized.toLowerCase();
  
  // Normalize special characters and accents
  normalized = normalized
    .replace(/[àáâãäå]/g, 'a')
    .replace(/[èéêë]/g, 'e')
    .replace(/[ìíîï]/g, 'i')
    .replace(/[òóôõö]/g, 'o')
    .replace(/[ùúûü]/g, 'u')
    .replace(/[ýÿ]/g, 'y')
    .replace(/[ñ]/g, 'n')
    .replace(/[ç]/g, 'c')
    .replace(/[ß]/g, 'ss')
    .replace(/[æ]/g, 'ae')
    .replace(/[œ]/g, 'oe')
    .replace(/ü/g, 'u')
    .replace(/ö/g, 'o')
    .replace(/ä/g, 'a')
    .replace(/ş/g, 's')
    .replace(/ğ/g, 'g')
    .replace(/ı/g, 'i')
    .replace(/ć/g, 'c')
    .replace(/č/g, 'c')
    .replace(/š/g, 's')
    .replace(/ž/g, 'z')
    .replace(/đ/g, 'd');
  
  return normalized;
}

/**
 * Get league slug for a competition name
 * Automatically removes year suffixes and handles variations
 */
export function getVerifiedLeagueSlug(competitionName: string): string | null {
  // Remove year suffix (e.g., " 2025/2026" or " 2025")
  const cleanName = competitionName.replace(/\s+\d{4}(\/\d{4})?$/g, '').trim();
  
  // Try direct exact match first (fastest)
  if (VERIFIED_LEAGUE_MAPPINGS[cleanName]) {
    return VERIFIED_LEAGUE_MAPPINGS[cleanName];
  }
  
  // Try case-insensitive exact match
  const lowerCleanName = cleanName.toLowerCase();
  for (const [key, value] of Object.entries(VERIFIED_LEAGUE_MAPPINGS)) {
    if (key.toLowerCase() === lowerCleanName) {
      return value;
    }
  }
  
  // Try normalized matching (handles country prefixes, accents, etc.)
  const normalized = normalizeLeagueName(competitionName);
  
  for (const [key, value] of Object.entries(VERIFIED_LEAGUE_MAPPINGS)) {
    const normalizedKey = normalizeLeagueName(key);
    if (normalizedKey === normalized) {
      return value;
    }
  }
  
  return null;
}
